### ISSUE TITLE
appimage-builder recipe

### ISSUE THREAD

**Issue by azubieta** [elegos/aws-glue-manager#1]
Here is a recipe I've made for packing aws-glue-manager using appimage-builder. Notice that the `deadsnakes` ppa is used to get python 3.9 and that the `after_bundle` section is used to install the dependencies using pipenv. It would be great if you could use a pyqt5 from the repositories as the one that gets installed from the python wheel includes lots of modules that you may not need.

```
# appimage-builder recipe see https://appimage-builder.readthedocs.io for details
version: 1
script:
  # Remove any previous build
  - rm -rf AppDir  | true
  - mkdir -p AppDir/usr
  # Make usr and icons dirs
  - mkdir -p AppDir/usr/src
  - mkdir -p AppDir/usr/share/icons/hicolor/scalable/apps
  # Copy the python application code into the AppDir
  - cp ../main.py ../ui ../lib  AppDir/usr/src -r
  # Add the application's icon
  - cp ../ui/icons/Arch_AWS-Glue_64.svg AppDir/usr/share/icons/hicolor/scalable/apps/awsgluemanager.svg

AppDir:
  path: ./AppDir

  app_info:
    id: name.giacomofurlan.AWSGlueManager
    name: AWSGlueManager
    icon: awsgluemanager
    version: latest
    # Set the python executable as entry point
    exec: usr/bin/python3.9
    # Set the application main script path as argument. Use '$@' to forward CLI parameters
    exec_args: "$APPDIR/usr/src/main.py $@"

  apt:
    arch: amd64
    sources:
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse'
      - sourceline: 'deb [arch=amd64] http://archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse'
        key_url: 'http://keyserver.ubuntu.com/pks/lookup?op=get&search=0x3b4fe6acc0b21f32'
      - sourceline: 'deb http://ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main'
        key_url: 'https://keyserver.ubuntu.com/pks/lookup?op=get&search=0xf23c5a6cf475977595c89f51ba6932366a755776'

    include:
      - python3.9
      - python3.9-distutils
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-render-util0
      - libxkbcommon-x11-0
      - libxcb-xinerama0
    exclude:
      # Avoid distribution default python packages from being included
      - python3.8-minimal
      - python3
  
  after_bundle: |
    # Set python 3.9 env
    export PYTHONHOME=${APPDIR}/usr
    export PYTHONPATH=${APPDIR}/usr/lib/python3.9/site-packages:$APPDIR/usr/lib/python3.9
    export PATH=${APPDIR}/usr/bin:$PATH
    # Set python 3.9 as default
    ln -fs python3.9 $APPDIR/usr/bin/python3
    # Install pip
    curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
    python3.9 get-pip.py
    # Install pipenv
    python3.9 -m pip install pipenv
    # Generate the requirements.txt file
    python3.9 -m pipenv lock -r > requirements.txt
    # Install application dependencies in AppDir
    python3.9 -m pip install --upgrade --isolated --no-input --ignore-installed --prefix=$APPDIR/usr wheel
    python3.9 -m pip install --upgrade --isolated --no-input --ignore-installed --prefix=$APPDIR/usr -r ./requirements.txt

  runtime:
    env:
      PYTHONHOME: '${APPDIR}/usr'
      # Path to the site-packages dir or other modules dirs
      # See https://docs.python.org/3/using/cmdline.html#envvar-PYTHONPATH
      PYTHONPATH: '${APPDIR}/usr/lib/python3.9/site-packages'

  
  files:
    exclude:
    - usr/share/man
    - usr/share/doc/*/README.*
    - usr/share/doc/*/changelog.*
    - usr/share/doc/*/NEWS.*
    - usr/share/doc/*/TODO.*

  test:
    fedora:
      image: appimagecrafters/tests-env:fedora-30
      command: ./AppRun
      use_host_x: true
    debian:
      image: appimagecrafters/tests-env:debian-stable
      command: ./AppRun
      use_host_x: true
    arch:
      image: appimagecrafters/tests-env:archlinux-latest
      command: ./AppRun
      use_host_x: true
    centos:
      image: appimagecrafters/tests-env:centos-7
      command: ./AppRun
      use_host_x: true
    ubuntu:
      image: appimagecrafters/tests-env:ubuntu-xenial
      command: ./AppRun
      use_host_x: true
AppImage:
  arch: x86_64
  update-information: guess
  sign-key: None
```

**Comment by elegos** [comment]
Hello @azubieta 

Thanks for the contribution!

I was wondering if I could avoid using PPAs in favour of an official / trusted respository. AFAIK I'm used too well with Fedora, which packages all the stable Python 3 releases :D - that was indeed my first option, to install Python 3.9 via APT.

Also I'll dig into package version of pyqt5, of if it's possible to exclude (`rm`?) all the libraries I don't use after pip install.

**Comment by azubieta** [comment]
> I was wondering if I could avoid using PPAs

I thought you didn't knew about it. In this case you can build it from sources and make sure to embed any other dependencies that may be missing.

> it's possible to exclude (rm?)

Yes, you can use rm  or the file exclude section to remove those files that are not required.

**Comment by elegos** [comment]
That's the point of the docker image which compiles Python 3.9 in /opt/python3.9, in order to copy it in AppDir/usr :smile: - so that I can use the docker image without having to compile Python each time.

I could for sure use a docker hub image prepared by myself and be fine with it. Another solution would be to use the Python official images (way better!), but I'd need a list of files that need to be transferred to AppDir/usr

**Comment by azubieta** [comment]
The `--generate` is will give you a file list instead of a packages list if ran in a system without apt. Maybe we could explore that path.

**Comment by elegos** [comment]
Update: I've realized an automated Python binaries docker image, which can be used as base for Python-based AppImage docker builds: [GitHub](https://github.com/elegos/python-precompiled/) -> [Docker Hub](https://hub.docker.com/r/giacomofurlan/python-precompiled)

**Comment by azubieta** [comment]
Awesome, I'll add a link from the appimage-builder python section.

**Comment by elegos** [comment]
I'm having a few problems with this approach, but I'm unsure if it's for the pre-compiled python libraries... thing is it now complains about the following, during the tests:

```
Cannot load library /app/usr/lib64/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: 
QLibraryPrivate::loadPlugin failed on "/app/usr/lib64/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so" : "Cannot load library /app/usr/lib64/python3.9/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so: "
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
```

As you can see the error does not expose the problem. Do you have any idea about? (see the `develop` branch)

P.S.
In the `files.include` part you can see I need to include different paths for different hosts (Fedora, Debian etc). I think that this might be improved if you could specify the file name and a list of possible roots where to find them (i.e. /usr/lib64, /lib/x86_64-linux-gnu etc). Also please note the work-around for `ld-linux-x86-64.so.2` (`script` part, "Fix non-debian-based libc ld library path (for tests)")

**Comment by azubieta** [comment]
Making a portable recipe is a tricky issue mainly because distributions change paths and names of the libraries as they please. My recommendation is to choose one and stick to it for all builds.

The issue is provably produced by some missing dependency of the plugin lib. Set the `LD_DEBUG=libs` environment in the test case to debug it.

https://appimage-builder.readthedocs.io/en/latest/reference/version_1.html#test

```
test:
  fedora:
    image: fedora:26
    command: "./AppRun main.qml"
    use_host_x: True
    env:
      LD_DEBUB: libs
```
